# Generated by Django 4.0.1 on 2023-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fram',
            field=models.CharField(choices=[('0', 'django'), ('1', 'flask'), ('2', 'featured')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
